name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  - name: Install SSH Key
    uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.RAG_SECRETKEY }} 
      known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RAG_SECRETKEY }}
          ARGS: "-avz --delete"
          REMOTE_HOST: ${{ secrets.RAG_ADDRESS }}
          REMOTE_PORT: ${{ secrets.RAG_PORT }}
          REMOTE_USER: ${{ secrets.RAG_USER }}
          TARGET: ${{ secrets.RAG_TARGET }}
          EXCLUDE: "/.git, /.github, /dist/, /node_modules/"
