name: deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RAG_SECRETKEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.RAG_PORT}} -H ${{ secrets.RAG_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p ${{ secrets.RAG_PORT }}" ./dist/ ${{ secrets.RAG_USER }}@${{ secrets.RAG_HOST }}:/var/www/pancake/
        

      - name: Rag
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RAG_HOST }}
          username: ${{ secrets.RAG_USER }}
          key: ${{ secrets.RAG_SECRETKEY }}
          port: ${{ secrets.RAG_PORT }}
          script: |
            cd /var/www/pancake/
            git fetch origin master
            git reset --hard FETCH_HEAD
            git clean -d -f --exclude secrets
            chown $(whoami) . # PM2 doesn't recognize root user from Github Actions

